M-TAN Authentication
senshi-x/ComdirectPostboxDownloader pull request #17
Opened 2021-07-25 17:44 UTC by martininka

added authentication via M-TAN (SMS)

2021-07-25 20:20 UTC, senshi-x commented
Thanks for the PR! looking good. Especially if handling mTAN really is that easy. Can't test it myself.

Not 100% sure about the shebang, though: Sadly, that is kinda OS-specific. I know of some Linux OS that use /usr/local/bin/python for their python3 setup. But I guess most at least have a symlink for python3 as well. Anyone have more insight on this?

2021-07-26 04:55 UTC, retiredHero commented
the documentation says: 
tldr; better: "#!/usr/bin/env python3", but in some Unix setups hardcoding is needed (like /usr/bin/python3).
So there is no "right" answer to this.


long:

"The /usr/bin/env form of shebang line has one further special property. Before looking for installed Python interpreters, this form will search the executable PATH for a Python executable. This corresponds to the behaviour of the Unix env program, which performs a PATH search."

Source: 
https://docs.python.org/3.7/using/windows.html#shebang-lines

and:
put an appropriate Shebang line at the top of the script. A good choice is usually 
#!/usr/bin/env python3
which searches for the Python interpreter in the whole PATH. However, some Unices may not have the env command, so you may need to hardcode /usr/bin/python3 as the interpreter path.

Source:
https://docs.python.org/3.7/using/unix.html#miscellaneous

2021-07-26 07:07 UTC, martininka commented
Ok it was a bad idea to combine two changes in one PR :)

Anyone able to test M-TAN? For sure it works for me :)

2021-07-26 09:02 UTC, martininka commented
@senshi-x: Do you want me to remove shebang, so that we only have on "feature request" to discuss?

2021-07-26 09:11 UTC, senshi-x requested changes
Just change the shebang to the recommended, and it's good to merge :) .

2021-07-26 09:11 UTC, senshi-x commented on main.py
> +#!/usr/local/bin/python3
change to #!/usr/bin/env python3, as per best practice recommendations

2021-07-26 10:18 UTC, senshi-x approved these changes

2021-07-26 10:18 UTC, merged

2021-07-26 10:18 UTC, senshi-x commented
Thanks again for the nice PR! <3

2021-07-26 10:48 UTC, martininka commented
de Rien :)

Thanks for your excellent work! Love this project!